export 'package:flutter_application_example/screens/animated_screen.dart';
export 'package:flutter_application_example/screens/avatar_screen.dart';
export 'package:flutter_application_example/screens/alert_screen.dart';
export 'package:flutter_application_example/screens/card_screen.dart';
export 'package:flutter_application_example/screens/home_screen.dart';
export 'package:flutter_application_example/screens/inputs_screen.dart';
export 'package:flutter_application_example/screens/listView1_screen.dart';
export 'package:flutter_application_example/screens/listView2_screen.dart';
export 'package:flutter/material.dart';
